version: "3.8"
services:
 consignments:
#   restart: always
  build: ./shippy-service
  ports:
        - 50051:50051
  environment:
       MICRO_SERVER_ADDRESS:
             ":50051"
       DB_HOST: "mongodb+srv://brayo:brayo@myblogcluster.976g4.mongodb.net/shippy?retryWrites=true&w=majority"
  depends_on:
       - vessel
       - user
#New service
 vessel: 
      image: vessel-service
      ports:
       - 50052:50051
      environment:
        MICRO_SERVER_ADDRESS: ":50051"
#New Service
 cli:
  build : ./shippy-client
  #restart : always
  depends_on:
    - consignments
    - vessel
# New Service
 user:  
  image: user-service
  restart : always
  ports:
   - 50053:50051
  environment:
   MICRO_SERVER_ADDRESS:
       ":50051"
  depends_on:
      - database

# #New service
 database:
   image: postgres
   environment:
     POSTGRES_PASSWORD: "postgres"
     POSTGRES_USER: "postgres"
   ports:
     - 5432:5432
   
