// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"gateway/handlers"
	"gateway/rabbitmq"
	"gateway/repository"
	"gateway/services"
	"log"
)

// Injectors from wire.go:

func ProvideVesselHandler(l *log.Logger, vesselQueue *rabbitmq.VesselQueue) *handlers.Vessel_hander {
	vesselRepository := repository.NewVesselRepository(l)
	vesselService := services.NewVesselService(vesselRepository, vesselQueue)
	vessel_hander := handlers.NewVessel(l, vesselService)
	return vessel_hander
}
